Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
  
Resources:
  myStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cloudformation-nested-stack-test-bucket.s3.ap-south-1.amazonaws.com/nested-otherstackfile.json
      Parameters:
        KeyName: !Ref SSHKey
        DBName: "mydb"
        DBUser: "admin"
        DBPassword: "admin@123"
        DBRootPassword: "root@123"
        InstanceType: t2.micro
        SSHLocation: "0.0.0.0/0"

Outputs:
  StackRef:
    Value: !Ref myStack
  OutputFromNestedStack:
    Value: !GetAtt myStack.Outputs.WebsiteURL